{"level":"dev.error","timestamp":"2024-01-30 19:28:50.964","logger":"localService","caller":"logService/main.go:18","msg":"这是一条error日志"}
{"level":"dev.error","timestamp":"2024-01-30 19:29:25.887","logger":"localService","caller":"logService/main.go:18","msg":"这是一条error日志"}
{"level":"dev.fatal","timestamp":"2024-02-19 17:58:52.177","logger":"localService","caller":"bootstrap/rabbitmq.go:65","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'userinfoqueue' in vhost '/videosystemdev'\""}
{"level":"dev.error","timestamp":"2024-02-19 18:57:30.178","logger":"localService","caller":"bootstrap/rabbitmq.go:76","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'userinfoqueue' in vhost '/videosystemdev'\""}
{"level":"dev.error","timestamp":"2024-02-19 18:57:30.178","logger":"localService","caller":"bootstrap/rabbitmq.go:86","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"dev.fatal","timestamp":"2024-02-19 18:57:30.178","logger":"localService","caller":"bootstrap/rabbitmq.go:99","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"dev.error","timestamp":"2024-02-20 10:42:43.119","logger":"localService","caller":"bootstrap/rabbitmq.go:65","msg":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"dev.error","timestamp":"2024-02-26 23:34:25.632","logger":"localService","caller":"bootstrap/rabbitmq.go:200","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-02-26 23:34:25.632","logger":"localService","caller":"bootstrap/rabbitmq.go:122","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-09 23:42:55.250","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-09 23:45:34.788","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-09 23:45:34.788","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-09 23:50:06.279","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-09 23:50:06.279","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-09 23:50:54.947","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-09 23:50:54.947","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-11 18:11:50.473","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-11 19:29:44.280","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-12 23:25:11.532","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-12 23:32:27.586","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-12 23:32:30.731","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-12 23:46:19.867","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-12 23:53:50.121","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-13 00:00:19.253","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-13 00:00:19.253","logger":"localService","caller":"bootstrap/basefunc.go:70","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-13 14:48:09.359","logger":"localService","caller":"bootstrap/basefunc.go:70","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-13 14:48:09.359","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-14 14:46:47.425","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-15 14:49:17.290","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-16 10:51:29.969","logger":"localService","caller":"bootstrap/basefunc.go:83","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-25 21:50:25.435","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 10:35:07.455","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:06:30.457","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-28 17:10:19.570","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:10:19.570","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-28 17:38:54.144","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:38:54.144","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:40:55.105","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:41:11.636","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-03-28 17:41:17.097","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-28 17:41:17.097","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-30 19:08:54.096","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-03-31 15:15:17.084","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-04-09 14:15:37.454","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 14:15:37.454","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-04-09 14:15:45.367","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 14:15:45.367","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-04-09 14:15:48.456","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 14:15:48.456","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 14:15:50.308","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 14:19:40.583","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 15:26:01.123","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-04-09 15:26:14.447","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-09 15:26:14.447","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-04-17 15:34:54.245","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-04-17 15:34:54.245","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.error","timestamp":"2024-05-22 17:05:37.798","logger":"localService","caller":"bootstrap/basefunc.go:68","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-05-22 17:05:37.798","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
{"level":"dev.fatal","timestamp":"2024-05-23 16:19:32.035","logger":"localService","caller":"bootstrap/basefunc.go:81","msg":"Exception (503) Reason: \"unexpected command received\""}
